docs_dir: src
site_name: Landspatientregisteret 3 - Technical documentation
pages:
- Home: index.md
- Governace: governance.md
- Documentation:
  - Interface aspects and usage: aspects.md
  - Submission scheme: submission-scheme.md
- Interface definition: interfacedefinitions.md
- Test environment: testenvironment.md
- Examples: examples.md  
- Related material and links: links.md
#- LPR 2 specifik dokumentation:
theme: readthedocs
extra:
  palette:
    primary: 'indigo'

repo_url: https://github.com/scandihealth/lpr3-docs/
edit_uri: edit/master/src

use_directory_urls: false
markdown_extensions: [fenced_code]
extra_css:
  - css/highlight.js/idea.css
  - css/theme-overrides.css