docs_dir: src
site_name: Landspatientregisteret 3 - Technical documentation
pages:
- Home: index.md
- Documentation:
  - Interface aspects and usage: aspects.md
- Interface definition: interfacedefinitions.md
- Examples: examples.md  
- Related material and links: links.md
#- LPR 2 specifik dokumentation:
theme: readthedocs
extra:
  palette:
    primary: 'indigo'

use_directory_urls: false
markdown_extensions: [fenced_code]
extra_css:
  - css/highlight.js/idea.css